version: '3.9'

services:
  plantuml:
    image: plantuml/plantuml-server
    container_name: plantuml-container
    ports:
      - "8080:8080"

  app:
    image: node:17-alpine3.14
    container_name: react-app-container
    volumes:
      - ./app:/usr/app:cached
    working_dir: /usr/app/src
    command: sh -c "yarn start"
    tty: true
    ports:
      - "3000:3000"
